AllCops:
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Enabled: false

Style/DotPosition:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
  
Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false